---
title: "GrowthRate_BacterialIsolates"
author: "Aied Garcia, Ariane L Peralta"
date: "Last updated on `r format(Sys.time(), '%d %B, %Y')`"
#output:
  #pdf_document: null
  #editor_options: null
  #fig_caption: yes
  #html_document: default
  #word_document: default
  #chunk_output_type: 
---


```{r setup, include=FALSE}
## Clears R environment
rm(list = ls())

#set working directory
setwd("~/GitHub/Bacterial_Growth_Curves")

## Load packages
library("ggplot2")
library("nlme")
library("bbmle")
library("optimx")
require("tidyverse")

## Load custom scripts
source("../bin/read.synergy.R")
```

# Import Data
```{r}
# EXAMPLE - importing data to prepare for graphing using ggplot2

Lysinibacillus <- read.synergy(input = "../data/Peralta_48well_24hr_WRC278M_WRC320MF.csv")

#Lysinibacillus spp. WRC320MF=D2,D4,D6; WRC278M = B2,B4,B6

#average replicate measurements
Lysinibacillus$LysMean_MF <- rowMeans(Lysinibacillus[,c("D2","D4","D6")])
Lysinibacillus$LysMean_M <- rowMeans(Lysinibacillus[,c("B2","B4","B6")])
dim(Lysinibacillus) #49 rows, 52 columns - columns 51 and 52 are the newly calculated values

#subset columns Time and mean growth rates from previous calculation
Lys_graph <- Lysinibacillus[c(1,51:52)]

# function stacks columns of mean growth
Lys_graph_long <- pivot_longer(Lys_graph, cols=2:3, names_to = "Treatment", values_to = "meanGrowth", values_drop_na = FALSE)
str(Lys_graph_long)
Lys_graph_long$Treatment <- as.factor(Lys_graph_long$Treatment)

# GRAPH
Lys <- ggplot(Lys_graph_long, aes(x = Time, y = meanGrowth, color=Treatment)) +
  geom_point() + geom_smooth() + theme_bw() +
  scale_color_manual(name="Treatment", values=c("gray70", "darkgreen"), labels = c("unfertilized/mowed", "fertilized/mowed")) + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.border = element_rect(colour = "black", fill=NA, size=1)) + 
  theme(axis.text.x = element_text(size=18,colour = "black", hjust=1),
        axis.title.x = element_text(size=18,face="bold")) +
  theme(axis.text.y = element_text(size=18,colour = "black"),
        axis.title.y = element_text(size=18,face="bold")) +
  theme(strip.text.x = element_text(size = 18,face="bold"),strip.text.y = element_text(size = 18))+
    coord_cartesian(ylim = c(0.1,0.5))+
  ggtitle("Lysinibacillus spp.") + 
            theme(axis.text=element_blank(), title=element_text(size=rel(1.25))) + 
            theme(plot.title = element_text(face = "italic")) +
  xlab("Time (hour)") + ylab("Absorbance 600 nm")

Lys

ggsave("../figures/Lys.png", plot=Lys, device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```
# Code for ASM Microbe 2022 poster - Smith, Garcia, Peralta
```{r}
Bac_BP <- read.csv("../data/WRC288_WRC246_GR.csv")

#average replicates
Bac_BP$meanGrowth <- rowMeans(Bac_BP[,c("Growth1","Growth2","Growth3")]) 
str(Bac_BP)

Pcorrugata <- ggplot(Bac_BP, aes(x = Hour, y = meanGrowth, color=Treatment)) +
  geom_point() + geom_smooth() + theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.border = element_rect(colour = "black", fill=NA, size=1)) + 
  theme(axis.text.x = element_text(size=18,colour = "black", hjust=1),
        axis.title.x = element_text(size=18,face="bold")) +
  theme(axis.text.y = element_text(size=18,colour = "black"),
        axis.title.y = element_text(size=18,face="bold")) +
  theme(strip.text.x = element_text(size = 18,face="bold"),strip.text.y = element_text(size = 18))+
    coord_cartesian(ylim = c(0.1,0.5))+
  ggtitle("Pseudomonas corrugata") + 
            theme(axis.text=element_blank(), title=element_text(size=rel(1.25))) + 
            theme(plot.title = element_text(face = "italic")) +
  xlab("Hour") + ylab("Absorbance 600 nm") +
  scale_color_manual(values=c("gray48","forestgreen"))

Pcorrugata

ggsave("../figures/Pcorrugata.png", plot=Pcorrugata, device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r}
Bac_BP_2 <- read.csv("../data/WRC283M_WRC281MF.csv")

#average replicates
Bac_BP_2$meanGrowth <- rowMeans(Bac_BP_2[,c("Growth1","Growth2","Growth3")]) 
str(Bac_BP_2)

Cpratensis <- ggplot(Bac_BP_2, aes(x = Hour, y = meanGrowth, color=Treatment)) +
  geom_point() + geom_smooth() + theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.border = element_rect(colour = "black", fill=NA, size=1)) + 
  theme(axis.text.x = element_text(size=18,colour = "black", hjust=1),
        axis.title.x = element_text(size=18,face="bold")) +
  theme(axis.text.y = element_text(size=18,colour = "black"),
        axis.title.y = element_text(size=18,face="bold")) +
  theme(strip.text.x = element_text(size = 18,face="bold"),strip.text.y = element_text(size = 18))+
    coord_cartesian(ylim = c(0.1,0.5))+
  ggtitle("Collimonas pratensis") + 
            theme(axis.text=element_blank(), title=element_text(size=rel(1.25))) + 
            theme(plot.title = element_text(face = "italic")) +
  xlab("Hour") + ylab("Absorbance 600 nm") +
  scale_color_manual(values=c("gray48","forestgreen"))

Cpratensis

ggsave("../figures/Cpratensis.png", plot=Cpratensis, device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r}
Bac_BP_3 <- read.csv("../data/WRC271M_WRC315MF.csv")

#average replicates
Bac_BP_3$meanGrowth <- rowMeans(Bac_BP_3[,c("Growth1","Growth2","Growth3")]) 
str(Bac_BP_3)

Pkoreensis <- ggplot(Bac_BP_3, aes(x = Hour, y = meanGrowth, color=Treatment)) +
  geom_point() + geom_smooth() + theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.border = element_rect(colour = "black", fill=NA, size=1)) + 
  theme(axis.text.x = element_text(size=18,colour = "black", hjust=1),
        axis.title.x = element_text(size=18,face="bold")) +
  theme(axis.text.y = element_text(size=18,colour = "black"),
        axis.title.y = element_text(size=18,face="bold")) +
  theme(strip.text.x = element_text(size = 18,face="bold"),strip.text.y = element_text(size = 18))+
    coord_cartesian(ylim = c(0.1,0.5))+
  ggtitle("Pseudomonas koreensis") + 
            theme(axis.text=element_blank(), title=element_text(size=rel(1.25))) + 
            theme(plot.title = element_text(face = "italic")) +
  xlab("Hour") + ylab("Absorbance 600 nm") +
  scale_color_manual(values=c("gray48","forestgreen"))

Pkoreensis

ggsave("../figures/Pkoreensis.png", plot=Pkoreensis, device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```

```{r}
Bac_BP_4 <- read.csv("../data/WRC263_WRC267.csv")

#average replicates
Bac_BP_4$meanGrowth <- rowMeans(Bac_BP_4[,c("Growth1","Growth2","Growth3")]) 
str(Bac_BP_4)

Aramosus <- ggplot(Bac_BP_4, aes(x = Hour, y = meanGrowth, color=Treatment)) +
  geom_point() + geom_smooth() + theme_bw() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.border = element_rect(colour = "black", fill=NA, size=1)) + 
  theme(axis.text.x = element_text(size=18,colour = "black", hjust=1),
        axis.title.x = element_text(size=18,face="bold")) +
  theme(axis.text.y = element_text(size=18,colour = "black"),
        axis.title.y = element_text(size=18,face="bold")) +
  theme(strip.text.x = element_text(size = 18,face="bold"),strip.text.y = element_text(size = 18))+
    coord_cartesian(ylim = c(0.1,0.5))+
  ggtitle("Arthrobacter ramosus") + 
            theme(axis.text=element_blank(), title=element_text(size=rel(1.25))) + 
            theme(plot.title = element_text(face = "italic")) +
  xlab("Hour") + ylab("Absorbance 600 nm") +
  scale_color_manual(values=c("gray48","forestgreen"))

Aramosus

ggsave("../figures/Aramosus.png", plot=Aramosus, device=NULL, path=NULL, scale=1, width=6, height=4, dpi=300, limitsize=TRUE)
```
Write out some growth functions.  In all these functions
A = the asymptotic body mass (or size)
k = growth rate constant
t = age or time
T_i = age or time at the inﬂection

```{r}
logistic<-function(A,k,t=t,T_i){
  A/1+exp(-k*(t-T_i))
}
gompertz<-function(A,k,t,T_i){
  A*exp(-exp(-k*(t-T_i)))
}
EVF<-function(A,k,t,T_i){
  A*(1-exp(-exp(k*(t-T_i))))
}
Bertalanffy<-function(A,k,t,T_i){
  A*(1-exp(-k*(t+T_i)))^3
}
```


First I will use nonlinear least squares to get good starting values for the mle fits
```{r}
d=data.frame(y=Bac_LC$Growth1,t=Bac_LC$Hour+1,Treatment=Bac_LC$Treatment)
d=na.omit(d)

logistic.=formula(y~ A/1+exp(-k*(t-T_i))|Treatment)#cant fit
Bertalanf=formula(y~ A*(1-exp(-k*(t+T_i)))^3|Treatment)#cant fit

gompz=formula(y~A*exp(-exp(-k*(t-T_i)))|Treatment)
m_g <- nlsList(gompz,start=list(A=150,k=0.5,T_i=25),data=d)
m_g

EVF=formula(y~A*(1-exp(-exp(k*(t-T_i))))|Treatment) 
m_E <- nlsList(EVF,start=list(A=150,k=0.5,T_i=25),data=d)
m_E
```


